import { Globe, MessageSquare, Film, GamepadIcon, Github, ArrowRight, type LucideIcon } from 'lucide-react';
import type { ViewId } from '@/types';
interface HomeViewProps { onNavigate: (view: ViewId) => void }
interface QuickLink { view: ViewId; label: string; description: string; icon: LucideIcon; gradient: string }
export default function HomeView({ onNavigate }: HomeViewProps) {
  const quickLinks: QuickLink[] = [
    { view: 'browser', label: 'Browser', description: 'Browse the web with Scramjet', icon: Globe, gradient: 'linear-gradient(135deg, #2d8cff, #8bd3ff)' },
    { view: 'chat', label: 'Chat', description: 'Talk with other aero. users', icon: MessageSquare, gradient: 'linear-gradient(135deg, #1464c4, #2d8cff)' },
    { view: 'movies', label: 'Movies', description: 'Stream movies and TV shows', icon: Film, gradient: 'linear-gradient(135deg, #1e74d6, #70b8ff)' },
    { view: 'games', label: 'Games', description: 'Play LuminSDK and GN Math games', icon: GamepadIcon, gradient: 'linear-gradient(135deg, #0b3b85, #2d8cff)' },
    { view: 'jsdelivr', label: 'GitHub Links', description: 'Generate CDN links at scale', icon: Github, gradient: 'linear-gradient(135deg, #64748b, #334155)' },
  ];
  return <div className="h-full overflow-y-auto p-6 animate-fade-in"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-4 mb-8"><img src="/c64e00f09ee3ebb80c04e28ab68acbf5.png" alt="aero." className="w-20 h-20 object-contain rounded-2xl" /><div><h1 className="text-3xl font-bold tracking-tight" style={{ color: 'var(--text-primary)' }}>Welcome to aero.</h1><p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>Your all-in-one browser, chat, media, and gaming platform</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{quickLinks.map((link) => { const Icon = link.icon; return <button key={link.view} onClick={() => onNavigate(link.view)} className="group flex items-center gap-4 p-5 rounded-2xl text-left transition-all hover:scale-[1.02] hover:shadow-lg" style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border)' }}><div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0" style={{ background: link.gradient }}><Icon size={24} className="text-white" /></div><div className="flex-1 min-w-0"><h3 className="font-semibold text-base" style={{ color: 'var(--text-primary)' }}>{link.label}</h3><p className="text-xs mt-0.5" style={{ color: 'var(--text-secondary)' }}>{link.description}</p></div><ArrowRight size={18} className="opacity-0 group-hover:opacity-100 transition-opacity shrink-0" style={{ color: 'var(--accent)' }} /></button>; })}</div><div className="mt-8 p-5 rounded-2xl" style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border)' }}><h3 className="font-semibold text-sm mb-2" style={{ color: 'var(--text-primary)' }}>About aero.</h3><p className="text-xs leading-relaxed" style={{ color: 'var(--text-secondary)' }}>aero. combines proxied browsing, real-time chat, movies, LuminSDK games, and scalable CDN link generation in one clean interface.</p></div></div></div>;
}
