import { ChevronLeft, ChevronRight, type LucideIcon } from 'lucide-react';
import type { ViewId } from '@/types';

interface NavItem { id: ViewId; label: string; icon: LucideIcon }
interface SidebarProps { open: boolean; onToggle: () => void; activeView: ViewId; onViewChange: (view: ViewId) => void; navItems: NavItem[]; user: { id: string; email: string; username: string } | null }

export default function Sidebar({ open, onToggle, activeView, onViewChange, navItems, user }: SidebarProps) {
  return <><aside className="flex flex-col transition-all duration-300 overflow-hidden border-r" style={{ width: open ? '220px' : '0px', background: 'var(--bg-secondary)', borderColor: 'var(--border)' }}><div className="flex items-center gap-2.5 px-4 h-12 border-b shrink-0" style={{ borderColor: 'var(--border)' }}><img src="/c64e00f09ee3ebb80c04e28ab68acbf5.png" alt="aero." className="w-7 h-7 object-contain rounded-lg shrink-0" /><span className="font-bold text-lg tracking-tight" style={{ color: 'var(--text-primary)' }}>aero.</span></div><nav className="flex-1 py-3 px-2 overflow-y-auto">{navItems.map((item) => { const Icon = item.icon; const active = activeView === item.id; return <button key={item.id} onClick={() => onViewChange(item.id)} className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg mb-0.5 transition-all text-sm font-medium" style={{ background: active ? 'var(--bg-tertiary)' : 'transparent', color: active ? 'var(--accent)' : 'var(--text-secondary)' }}><Icon size={18} className="shrink-0" /><span className="truncate">{item.label}</span>{active && <div className="ml-auto w-1.5 h-1.5 rounded-full" style={{ background: 'var(--accent)' }} />}</button>; })}</nav><div className="px-3 py-3 border-t shrink-0" style={{ borderColor: 'var(--border)' }}>{user ? <div className="flex items-center gap-2.5 px-1"><div className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold shrink-0" style={{ background: 'var(--accent)', color: 'var(--bg-primary)' }}>{user.username.charAt(0).toUpperCase()}</div><div className="min-w-0"><p className="text-xs font-medium truncate" style={{ color: 'var(--text-primary)' }}>@{user.username}</p><p className="text-xs" style={{ color: 'var(--text-muted)' }}>Signed in</p></div></div> : <p className="text-xs px-1" style={{ color: 'var(--text-muted)' }}>Sign in via Settings to sync</p>}</div></aside><button onClick={onToggle} className="flex items-center justify-center w-5 border-r shrink-0 transition-colors hover:opacity-80" style={{ background: 'var(--bg-secondary)', borderColor: 'var(--border)', color: 'var(--text-muted)' }}>{open ? <ChevronLeft size={14} /> : <ChevronRight size={14} />}</button></>;
}
